[tools]
colima = { version = "0.10.3", os = ["macos"] }
docker-cli = { version = "29.8.1", os = ["macos", "linux"] }
go = "1.27.1"
helm = { version = "4.3.0", os = ["macos", "linux"] }
kubectl = { version = "1.37.1", os = ["macos", "linux"] }
lima = { version = "2.2.0", os = ["macos"] }
